# 配置文件加密key
server:
  port: 9999
  servlet:
    context-path: /system

jasypt:
  encryptor:
    password: G0CvDz7oJn6

spring:
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-test-query: SELECT 1
    dynamic:
      primary: master #设置默认的数据源,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/yyy?Unicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
          username: root
          #加密数据库密码，具体加密方式参考mybatis-plus，本项目有单独的加密工具类，EncryptorPasswordUtils.class
          password: ENC(Yq+dswLkrMgDlSY46qC0gvzq2Ra8flqTH2C99RVk/ds=)
          driverClassName: com.mysql.cj.jdbc.Driver
  banner:
    location: system.txt

  devtools:
    restart:
      enabled: false  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

#逻辑删除配置
mybatis-plus:
  configuration:
    cache-enabled: false
  global-config:
    logic-delete-value: 1
    logic-not-delete-value: 0

logging:
  level:
    com.yyy.system.dao: debug

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  #  thumb-image:             #缩略图生成参数
  #    width: 150
  #    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 127.0.0.1:22122



uploadFile:
  #HOST
  host: http://127.0.0.1
